### PR TITLE
Dev pull request

### PR DESCRIPTION
**Pull request by maelfosso**
We finished working on the project.
Please review our code and tell us what we could do to improve it.

### CODE REVIEW

**Comment by rvvergara** [comment]
Hi @maelfosso and @bellom,

Hey awesome time joing you guys yesterday in your first ever Standup Meeting. It's my pleasure now to give you your first ever code review in Microverse.

I used this tool (http://raw.githack.com) to check how your web app looks like live.. I suggest you also use this tool (copy the link to your project's index.html link and paste it in the input box and voila it will generate for you a live demo link). The page looks great! Awesome job!

Here are a number of things I hope you can improve on the project:

1. Pls run your index.html file into the HTML Validator tool (https://validator.w3.org). When I ran it, there were 23 errors. Though some of these errors are not deal breakers, there are a lot that you should really fix. 

2. README.md -> It would be great if you could provide more information here. Normally, aside from the title of your project, which you already put, you would wanna include the ff:
- a short description of the project (i.e, what particular skills/technologies you wanna highlight in it? In this instance you wanna let the world know that this Youtube clone utilizes image and video embedding for the main video and the thumbnails at the side)
- Your names and links to your respective Github repositories (this is a good tool to learn how to use markdown: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)
- Of course, a link to the live demo (using the raw.githack.com link I mentioned above). This is so anybody (including us code reviewers) who wants to check out what you did here will see the awesomeness you produced! :)

3. While this is just a small project and directory setup may not be that critical yet, it's still good practice to have a separate folder for your css (i.e, css/ folder), the same way you did for images and videos.. Furthermore, all of your project's assets (including css, images and videos, and later on js scripts) will be better put in an 'assets' folder. Inside this assets folder you will still have separate folders for your css, images, videos, js etc.

4. Repetitive lines: We are all guilty of this, no matter how long we've been programming. In your main.css file there are some lines that were duplicated. For instance, the style `position: relative` appeared 5 times (lines 69, 313, 321, 375 and 389). We would love to 'dry' (short for Don't Repeat Yourself) out our code as much as possible. So I suggest, for example in this case, to just group all the elements using this `position: relative` style into a comma-separated selector group as such:

```
.video-player, .video .time, .video .clock, .switch, .switch input + label {
position: relative;
}
```
This is all for now. After you make the above changes, just please submit another code review request, we all will be happy to help you further :)

Ryan

**Comment by bellom** [comment]
Thanks Ryan

**Comment by maelfosso** [comment]
Thank you Ryan !

**Comment by maelfosso** [comment]
@rvvergara please I have some questions about how to use validators.w3.org 

Do we have to use it with the link from the *index.html* from ``dev`` branch that is ``https://github.com/bellom/youtube-clone/blob/dev/index.html`` or from the link generated by http://raw.githack.com

Because when I use this link https://github.com/bellom/youtube-clone/blob/dev/index.html there are many errors that I don't recognize, I don't see in our code but with the link generated when I introduce https://github.com/bellom/youtube-clone/blob/dev/index.html into http://raw.githack.com , the errors are comprehensible.

So I'm a bit confused please

**Comment by rvvergara** [comment]
Just copy the whole HTML code in your index.html (not the link of your index.html) and then paste it into the "Validate By Direct Input" option in the validator. Then click "Check"

**Comment by bellom** [comment]
Ok

**Comment by rvvergara** [comment]
I ran it against the Validator and yeah no more errors :) Great job! Although I don't notice you made changes in the CSS file (for the repetitive lines I mentioned before). And also please remember to fill up your README (with the informationI mentioned in the initial review). After you made these changes please submit a code review request again. Then hopefully by that time ill finally give a :+1:

**Comment by bellom** [comment]
Code repetition have been worked on. We now have dry code .....

**Comment by rvvergara** [comment]
Yeah I notice it now! Great job on the README! :) 

For this you will get a 

# :+1: 

You can now merge this into your Master and Complete the Project. Great work!

**Comment by bellom** [comment]
Thanks Ryan.
After merge, we are to complete the project by filling the second form and
submitting the website link right ?
And can we use the website link generated from raw.githack?

**Comment by rvvergara** [comment]
Yes, fill up the Project Completion Form. In that form you are to paste a link to this project's Github repository and also a link to the live demo (using the githack link)

**Comment by bellom** [comment]
Thanks.
I have a question.
It was great using githack for code review on development branch.
Can we use GitHub Pages to create website link once the code as been reviewed? 
Reason:  GitHub link looks shorter than GitHack. To make the website link a dry link

**Comment by bellom** [comment]
Ryan you there......

**Comment by rvvergara** [comment]
No problem, you may use Github pages either before or after completion :) The important thing is having a live demo

**Comment by bellom** [comment]
Awesome, just wanna make the website link a dry link

**Pull request merged**
